bloggers.json

//CC: @piotrpietrzak (aka Peter Accounting ;) )

Add Piotr Pietrzak blog

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailGenerator.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailSender.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/people/PersonRepository.java
src/main/resources/mail_templates/blog_summary.st
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailGeneratorSpec.groovy

new "Person" entities are taken by date_added field

#27 Add info about new blogs added since last newsletter to sent newsletter

---

bloggers.json

Add Tomasz Kalkosiński's refaktor blog

---

bloggers.json

Hi,
I'm adding my blog (http://blog.wittchen.biz.pl/) to the list.
Regards,
Piotr

adding blog.wittchen.biz.pl to bloggers.json

---

src/main/resources/mail_templates/blog_summary.st

To avoid funny mix of PL and EN in one sentence we can translate this to EN partially/entirely.

"Od" to "by" conversion because every title is in English. 

---

.gitignore
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/resources/application-dev.yaml

1. Improved development setup procedure and updated README to be even more meaningful. From now on there is no need to alter [`application-dev.yml`](https://github.com/goostleek/jvm-bloggers/blob/70012c59ced5bff3ab476fcda1cc6fae5c11e3dc/src/main/resources/application-dev.yaml) by changing `datasource.url`. The property can be set from gradle or docker command line. In this way there is no risk that one can accidentally commit altered `application-dev.yml`.
2. Updated gradle wrapper to the latest version (which is _2.11_ at the moment of writing this).
3. Updated [`.gitignore`](https://github.com/tdziurko/jvm-bloggers/commit/0ee5ef163493651f4f9eac7b478c920f840800d9) to prevent tracking build artifacts and IDE specific files. The file was generated using https://www.gitignore.io.

Improved development setup

---

bloggers.json

Dodałem swojego bloga, dołącz jak możesz ;)
btw też startuję w daj się poznać, także niedługo pojawi się kilka nowych wpisów ;)

http://michalgellert.blogspot.com/

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepository.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/utils/DateTimeUtilities.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/AdminDashboardPage.html
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/AdminDashboardPage.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/DashboardNewPostsCounterModel.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/counters/NewPostsCounterModel.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/utils/DateTimeUtilitiesSpec.groovy

added new posts counter in admin dashboard

added new posts counter in admin dashboard

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/LogMailSender.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/MailSender.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/MailgunSender.java

Send emails to log on dev and test profile

---

README.md
src/main/java/pl/tomaszdziurko/jvm_bloggers/InitialBlogDataPopulationTrigger.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/InitialBlogDataPopulationTriggerSpec.groovy

Initial database population with bloggers and posts data

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/mailing/MailingPage.html

Column that contain buttons was too narrow. Column resized to md-3 and set text alignment to the right.

[#116] Mailing form buttons bug fixed

---

build.gradle
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/AggregatedRssFeedProducer.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/BlogPostsController.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/NewBlogPostStoringActor.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/RssCheckingActor.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/RssEntryWithAuthor.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailGenerator.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/utils/SyndFeedProducer.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/AggregatedRssFeedProducerSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/BlogPostsControllerSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/NewBlogPostStoringActorSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/RssCheckingActorSpec.groovy
src/test/resources/pl/tomaszdziurko/jvm_bloggers/blog_posts/expected-rss.xml

Update Rome to 1.5.1

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataUpdater.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/domain/Blog.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/json_data/BloggerEntry.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/login/LoginPage.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/login/attack/BruteForceAttackMailGenerator.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/RssCheckingActorSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataUpdaterSpec.groovy

Refactoring includes removal of unused logger variables (compiler warnings) from `LoginPage` and `BruteForceAttackMailGenerator` and removal of hand-crafted constructors with Lombok annotations from `Blog` and `BloggerEntry`.

Refactroing: removed boiler-plate code by replacing it by Lombok annotations

---

src/test/groovy/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailSenderSpec.groovy

Disabled problematic [test case](https://github.com/tdziurko/jvm-bloggers/pull/160/files#diff-f6a976658ee163fa6b8b92ac544d5cdaR35) until #157 is fixed.

Disabled one problematic BlogSummaryMailSenderSpec test case till #157 is resolved

---

.gitconfig
CONTRIBUTING.md

Added .gitconfig with core.autocrlf set to input

---

bloggers.json

New private blog http://ggajos.com

Added new personal blog entry to bloggers.json

---

bloggers.json

New blog http://cslysy.github.io added

New blog http://cslysy.github.io added

---

bloggers.json

Nowy blog, stary nadal jeszcze aktywny, na razie niech leży jeszcze.

Add new blog kto.so

---

README.md
src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcher.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataUpdater.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/domain/BlogType.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailGenerator.java
src/main/resources/application.yaml
src/main/resources/db/changelog/add_video_blogs_to_template.sql
src/main/resources/db/changelog/db.changelog.xml
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy
src/test/resources/pl/tomaszdziurko/jvm_bloggers/blogs/test_videos.json
videos.json

Added video blogs as new type of content. Closes #174

---

companies.json

Adding Codete Blog

---

src/main/resources/blogs/bloggers.json

Added _devtalk.pl_ podcast by Maciej Aniserowicz.

Added devtalk podcast

---

src/main/resources/blogs/companies.json

Adding Sages to companies blogs

---

README.md

(And hope you like it. That's all I could offer these days) Use it however you want. Kudos for your great work!

[MINOR] Rewording README hoping it makes for a more pro experience

---

src/main/resources/blogs/bloggers.json

I hope I'm not late to the party.

Adds Szymon Biliński's blog

---

src/main/java/com/jvm_bloggers/TimeConstants.java
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostsFetchingScheduler.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetchingScheduler.java
src/main/java/com/jvm_bloggers/core/newsletter_issues/PublishNewNewsletterIssueScheduler.java
src/main/resources/application.yaml

This will allow to change cron configuration without recompile redeploy.

Moving cron configuration to properties

---

build.gradle
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressActionPanel.html
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressActionPanel.java
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressPage.html
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressPage.java
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressPage.properties
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressPageRequestHandler.java
src/main/java/com/jvm_bloggers/admin_panel/mailing/MailingAddressUniquenessValidator.java
src/main/java/com/jvm_bloggers/core/mailing/domain/MailingAddress.java
src/main/java/com/jvm_bloggers/core/mailing/domain/MailingAddressRepository.java
src/test/groovy/com/jvm_bloggers/MockSpringContextAwareSpecification.groovy
src/test/groovy/com/jvm_bloggers/admin_panel/mailing/MailingAddressPageSpec.groovy
src/test/groovy/com/jvm_bloggers/core/mailing/domain/MailingAddressRepositorySpec.groovy

I am wondering if this way of uniquest check (MalingAddress.address) is acceptable (what other options do we have?)

MailingAddress table (create/edit/delete)

---

src/main/resources/blogs/companies.json

Added Consdata company blog. Fullstack development with strong focus on backend/jvm.

Added Consdata company blog.

---

docker-compose.yml
jvm-bloggers.sh
src/main/java/com/jvm_bloggers/kafka/MessagesPublisher.java
src/main/resources/application.yaml

Add `jvm_bloggers-kafka 127.0.0.1` entry /etc/hosts

added twitter image + fix kafka dockerization. 

---

src/main/java/com/jvm_bloggers/JvmBloggersApplication.java
src/main/java/com/jvm_bloggers/JvmBloggersConfiguration.java
src/main/java/com/jvm_bloggers/admin_panel/moderation/FetchingDataPanel.java
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostsFetcher.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetcher.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/PreventConcurrentExecutionSafeguard.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetcherSpec.groovy

Initial blog posts population stopped working after #280. This PR makes it working again.

Fixed initial blog posts population broken after introducing asynchronism into fetchers

---

src/main/resources/blogs/bloggers.json

https://blog.pchudzik.com RSS added

adding Paweł Chudzik's blog

---

src/main/resources/blogs/bloggers.json

Hi Tomasz
Thank You for help, I've just changed path to appropriate one.
Best regards
TJ

Update bloggers.json - changed TJ's Blog Atom path

---

src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetcher.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/json_data/BloggerEntry.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdaterSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/json_data/BloggerEntrySpec.groovy

Returning fetching status. Fix #304

---

src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggerChangedVerifier.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetcher.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/UpdateStatistic.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/UpdateStatus.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/json_data/BloggersData.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggerChangedVerifierSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdaterSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/UpdateStatisticSpec.groovy

A follow up to #304 and #305
Some further refactoring of `BloggersDataUpdater` in order to ensure more pure behaviour and remove decrease method visibility.

304-followup

---

src/main/java/com/jvm_bloggers/frontend/all_issues/all_issues_panel/IssuesInMonthPanel.html

Adding little code, which fixes reported issue.

Fixes #309

---

src/main/resources/blogs/bloggers.json

My new blog in its early stage. At the moment one JavaScript (yeah, not-so-JVM ;-) ) related post and second one touching Git, IntelliJ, and Gradle. Plans for near future: more posts about Kotlin and IntelliJ.
If this is not enough to join blogs list at the moment - just let me know :-)

Added timbercode.pl, Paweł Barszcz's blog

---

src/main/resources/blogs/bloggers.json

Lukasz K blog address has changed

---

src/main/resources/blogs/bloggers.json

Adding my new blog mainly related to young programmer's craftsmanship: http://sprawnyprogramista.pl
BTW: is that `jsonId` crucial for list of blogs working? I see it may cause conflicts with other entries.

Add Sprawny Programista blog

---

src/main/resources/blogs/bloggers.json

Change protocol to https in koziolekweb

---

src/main/resources/blogs/bloggers.json

Remove doubled HTTP prefix in URI

---

src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/newsletter_panel/BlogLinksSection.html
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/newsletter_panel/BlogPostLinksSection.html

Blog posts and authors are now opened in new tabs.

Fixes #290

---

src/main/resources/blogs/bloggers.json

Added paweldobrzanski.pl blog

---

src/main/resources/blogs/bloggers.json

I wonder if jvm bloggers is also used by juniors and beginners :)

Adding a blog about Java related stuff for begginers

---

src/main/resources/blogs/bloggers.json

Updated rss feed for Grzegorz Gajos blog

Updated rss feed for Grzegorz Gajos blog

---

src/main/java/com/jvm_bloggers/frontend/public_area/all_issues/AllIssuesPageBackingBean.java
src/test/groovy/com/jvm_bloggers/frontend/public_area/all_issues/AllIssuesPageBackingBeanSpec.groovy

This PR will fix sorting issue mentioned in #365.

Fix archive sorting.

---

build.gradle
src/main/java/com/jvm_bloggers/core/blogpost_redirect/click_counter/ClicksStoringActor.java
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/NewBlogPostStoringActor.java
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/RssCheckingActor.java
src/main/java/com/jvm_bloggers/frontend/admin_area/blogs/BlogActionPanel.java
src/main/java/com/jvm_bloggers/frontend/admin_area/counters/NewPostsCounterModel.java
src/main/java/com/jvm_bloggers/frontend/admin_area/counters/PostsWaitingForModerationCounterModel.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingAddressActionPanel.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingAddressPage.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingPage.java
src/main/java/com/jvm_bloggers/frontend/admin_area/moderation/DateOfLastFetchingDataModel.java
src/main/java/com/jvm_bloggers/frontend/admin_area/moderation/ModerationActionPanel.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/NewBlogPostStoringActorSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/RssCheckingActorSpec.groovy

Akka and Wicket dependencies update contains breaking API changes - refactor was required.
The update also closes #363.

Maintenance: dependencies update

---

src/main/java/com/jvm_bloggers/core/github/ContributorsService.java
src/main/java/com/jvm_bloggers/core/github/GithubProperties.java
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorsPage.html
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorsPage.java
src/main/resources/application.yaml
src/test/groovy/com/jvm_bloggers/core/github/ContributorsServiceSpec.groovy

Clean up the mess, and fixing #370

fixes #370

---

src/main/resources/static/assets/css/custom.css
src/main/resources/static/assets/css/style.css

Just removed margin-top and here is the effect:
/cc @jaceklaskowski

Fix navigation dropdown.

---

src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/NewBlogPostStoringActor.java
src/main/java/com/jvm_bloggers/entities/blog_post/BlogPostRepository.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/NewBlogPostStoringActorSpec.groovy

I have written a simpler solution that one agreed in #301 , not sure if we should go this way or choose the more complicated approach with additional column.
WDYT?

Check for blog post existence no matter what protocol is used (http/https)

---

src/main/java/com/jvm_bloggers/frontend/public_area/AbstractFrontendPage.html
src/main/resources/static/assets/css/custom.css
src/main/resources/static/assets/css/style.css

On following image there are two small (but annoying for me bugs):
1. Fork me on GitHub ribbon in under navbar (fixed z-index)
2. 'Wydanie'&'Archiwum' headers are too close to navbar (added padding-top: 15 px)
Before:
After:

Minor, but annoying visual bugfixes

---

.travis.yml
src/main/java/com/jvm_bloggers/domain/query/blog_post_for_listing/BlogDisplayDetails.java
src/main/java/com/jvm_bloggers/frontend/public_area/blogs/AbstractBlogsPageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/public_area/blogs/BlogPostsPageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/public_area/blogs/BlogPostsPageRequestHandler.java
src/main/java/com/jvm_bloggers/frontend/public_area/blogs/BlogsRequestHandler.java

My PR (https://github.com/jvm-bloggers/jvm-bloggers/pull/409) did not include fix for NSE. This PR will fix it.
Sorry for the mess.

Fix for NotSerializableException thrown by Wicket

---

src/main/java/com/jvm_bloggers/frontend/public_area/common_layout/HeaderFrontend.html
src/main/java/com/jvm_bloggers/frontend/public_area/common_layout/HeaderFrontend.java
src/main/java/com/jvm_bloggers/frontend/public_area/rss/RssInformationPage.html
src/main/java/com/jvm_bloggers/frontend/public_area/rss/RssInformationPage.java
src/main/java/com/jvm_bloggers/frontend/public_area/rss/RssInformationPageBackingBean.java
src/main/resources/static/assets/css/custom.css
src/test/groovy/com/jvm_bloggers/frontend/public_area/rss/RssInformationPageSpec.groovy

I've just added very simple RSS feed information page - if something is not clear as it should be (especially descriptions), please don't complain too much here, I'll try to fix it :)

#375 Added simple RSS feed info page

---

src/main/java/com/jvm_bloggers/frontend/public_area/rss/RssInformationPage.java

Introduced small fix proposed by @goostleek in the #418 PR.

Cosmetic fix in the RssInformationPage

---

src/main/java/com/jvm_bloggers/core/rss/AggregatedRssFeedProducer.java
src/main/java/com/jvm_bloggers/core/rss/BlogPostsController.java
src/main/java/com/jvm_bloggers/core/rss/converters/SyndFeedToJsonConverter.java
src/test/groovy/com/jvm_bloggers/core/rss/TestSyndFeedProvider.groovy
src/test/groovy/com/jvm_bloggers/core/rss/converters/SyndFeedJsonMessageConverterSpec.groovy
src/test/groovy/com/jvm_bloggers/core/rss/converters/SyndFeedToJsonConverterSpec.groovy
src/test/resources/com/jvm_bloggers/core/rss/converters/expected-rss.xml

I've made some code simplifications in `BlogPostsController`. Also corrected behavior of some tests, please find details in comments.

Minor code refactoring

---

src/main/resources/blogs/bloggers.json

Add www.dmydlarz.com

---

src/main/resources/blogs/bloggers.json

Added itblues.pl

---

src/main/java/com/jvm_bloggers/core/social/twitter/TweetContentGenerator.java
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetContentGeneratorSpec.groovy

Filter out blogs without Twitter handle while generating Twitter message

---

src/main/resources/blogs/bloggers.json

In preparations to new year resolutions it's time to publish something. Let's start form simple pull request which is not a publication yet, but have some text included. :)

- Added dywicki.pl blog

---

src/main/resources/blogs/bloggers.json

Hello everyone :) Wanted to add a blog where together with Marcin we started writing about DDD and other topics related to the boundary between business and IT.

Added itlibrium.com

---

src/main/resources/blogs/companies.json

Przycinam feed rss tylko do wpisów technicznych ;-)

Blog firmowy Consdata - przycięcie feed tylko do wpisów technicznych

---

src/main/resources/blogs/bloggers.json

I moved my posts on Medium to the publication to filter out comments I write in posts of other people.

Pawel Urban's RSS URL changed

---

src/main/resources/blogs/bloggers.json

This pull request updates feed URL of my programming-related blog. Thanks!

Szymon Stepniak blog feed URL update

---

src/main/resources/blogs/bloggers.json

This pull request updates feed URL of my programming-related blog. Thanks!

Update Grzegorz Piwowarek feed URL

---

src/main/resources/blogs/videos.json

I recently started YouTube channel - all around Java, Spring, Kotlin, Cloud etc. Hopefully valuable content for JVM Bloggers :-)

Add Spring Academy YouTube channel

---

src/main/resources/blogs/bloggers.json

Hi, I've added my personal blog, hope you enjoy it.

Add chi.pl blog

---

src/main/resources/blogs/bloggers.json

feed source changed

---

src/main/resources/blogs/companies.json

Added link to a new blog by JIT Solutions (www.jitsolutions.pl).

Added JIT Solutions blog link

---

src/main/resources/blogs/videos.json

Zgodnie z ustaleniami z @tdziurko, dodałem Bydgoszcz JUG do zbioru wideo.
Dzięki i pozdrawiam,
Sebastian

Added Bydgoszcz JUG video feed

---

CONTRIBUTING.md
README.md

Updated broken links in markdown files

---

src/main/resources/blogs/bloggers.json

add new blog socodeit.pl

---

src/main/resources/blogs/bloggers.json

Hello, Adding my blog to the mix. Thanks :)

Add Igor Kupczyński blog

---

src/main/resources/blogs/bloggers.json

Hi, Please add my blog to blogger list

Add DevRev.pl blog

---

src/main/resources/blogs/bloggers.json

This is the only change for adding Twitter account.

Add Twitter account to Pura Dawid's blog

---

src/main/resources/blogs/bloggers.json

add cupofcodes.pl blog

---

src/main/resources/blogs/companies.json

It would be superb cool if you add our blog to your newsletter. We know that it's a little bit dead, BUT...
the new article is coming this week! 🚀

add Applantic blog

---

src/main/resources/blogs/bloggers.json

Update Twitter handle

---

src/main/resources/blogs/bloggers.json

Włodek Krakowski's blog about refactoring.
I would like to join the list of bloggers to make subject of refactoring more popular.

Włodek Krakowski's blog about refactoring

---

README.md
src/main/java/com/jvm_bloggers/core/blogpost_redirect/LinkGenerator.java
src/main/java/com/jvm_bloggers/core/newsletter_issues/NewNewsletterIssuePublisher.java
src/main/java/com/jvm_bloggers/core/social/fb/FacebookMessageGenerator.java
src/main/java/com/jvm_bloggers/core/social/fb/FacebookMessageTemplate.java
src/main/java/com/jvm_bloggers/core/social/fb/FacebookPostProducer.java
src/main/java/com/jvm_bloggers/domain/command/top_posts_summary/GenerateTopPostsInMonthSummaryCommandHandler.java
src/main/java/com/jvm_bloggers/domain/command/top_posts_summary/TopPostsSummaryGenerated.java
src/main/resources/application.yaml
src/test/groovy/com/jvm_bloggers/core/rss/AggregatedRssFeedProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/fb/FacebookMessageGeneratorSpec.groovy
src/test/groovy/com/jvm_bloggers/domain/command/top_posts_summary/GenerateTopPostsInMonthSummaryCommandHandlerIntegrationSpec.groovy

Unfortunately I am not able to test it in any way besides integration testing for added facebook post row in DB table. There is also a little bit of refactoring in Facebook messages.

Facebook top post summary 405

---

src/main/resources/blogs/videos.json

Nagrania z Bydgoszcz IT Conference

Dodanie kanału YT konferencji bITconf

---

src/main/resources/blogs/videos.json

adding channel Programuj z Bykiem: https://www.youtube.com/channel/UCjWnQvpQgSRLeDEYQC0ZuLg

adding channel Programuj z Bykiem

---

src/main/resources/blogs/videos.json

Add Programistok YT channel

---

src/main/resources/blogs/videos.json

Update 'Programuj z Bykiem' channel_id

---

src/main/resources/blogs/bloggers.json

Added szkolatestow.online/blog

Add szkolatestow.online/blog to bloggers.json

---

src/main/resources/blogs/bloggers.json

Add new blog SolidSoft .pl

---

src/main/resources/blogs/bloggers.json

My personal blog - this time from the right account ;)

Add Łukasz Dziedziul's blog

---

src/main/resources/blogs/bloggers.json

Looks like this domain, is, ekhem, obsolete ;-)

Removing tidyjava.com

---

src/main/java/com/jvm_bloggers/core/blogpost_redirect/RedirectController.java
src/main/java/com/jvm_bloggers/core/newsletter_issues/PublishNewNewsletterIssueScheduler.java
src/main/java/com/jvm_bloggers/core/rss/converters/SyndFeedToJsonConverter.java
src/main/java/com/jvm_bloggers/schedulers/top_posts_summary/TopPostsInPreviousMonthSummaryScheduler.java
src/main/java/com/jvm_bloggers/utils/DateTimeUtilities.java
src/main/java/com/jvm_bloggers/utils/NowProvider.java
src/main/java/com/jvm_bloggers/utils/ZoneTimeProvider.java
src/test/groovy/com/jvm_bloggers/TestTimeProvider.groovy
src/test/groovy/com/jvm_bloggers/core/blogpost_redirect/RedirectControllerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostFactorySpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/RssCheckingActorSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetcherSpec.groovy
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdaterSpec.groovy
src/test/groovy/com/jvm_bloggers/core/mailing/sender/EmailSendingSchedulerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/rss/AggregatedRssFeedProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/rss/IssuesRssFeedProducerTest.groovy
src/test/groovy/com/jvm_bloggers/core/rss/converters/SyndFeedToJsonConverterSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/fb/FacebookPostProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/fb/publisher/FacebookPublishingSchedulerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetContentGeneratorSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/publisher/TwitterPublishingSchedulerSpec.groovy
src/test/groovy/com/jvm_bloggers/domain/query/blog_statistics_for_listing/BlogStatisticsForListingQuerySpec.groovy
src/test/groovy/com/jvm_bloggers/entities/blog_post/BlogPostSpec.groovy
src/test/groovy/com/jvm_bloggers/entities/newsletter_issue/NewsletterIssueRepositorySpecBase.groovy
src/test/groovy/com/jvm_bloggers/frontend/admin_area/login/LoginPageSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/admin_area/login/attack/BruteForceAttackMailGeneratorSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/admin_area/mailing/MailingPageSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/admin_area/moderation/BlogPostItemPopulatorSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/public_area/blogs/BlogPostsPageSpec.groovy

I've extracted NowProvider as an interface, the old NowProvider has beem  renamed to ZoneTimeProvider and now TestTimeProvider implements NowProvider interface instead of extending ZoneTimeProvider

Extract an interface for providing the current date

---

docker-compose.yml
jvm-bloggers-local.sh
jvm-bloggers.sh
src/main/resources/application.yaml

Add caddy reverse proxy in front of the JVM Bloggers

---

src/main/resources/blogs/bloggers.json

I've changed my surname and Twitter handle by association.
References:
* [LinkedIn](https://www.linkedin.com/posts/sjednac_ive-changed-my-surname-bili%C5%84ski-to-my-activity-6644571756659003392--ad6)
* [Site](http://mintbeans.com/)

Update personal details

---

src/main/resources/blogs/bloggers.json

Added wprostychslowach.pl, thx

Up bloggers.json

---

src/main/resources/blogs/bloggers.json

Additionally, Prettier reformatted a few lines - hope that's not a problem :)

Add bartoszgajda.com blog to bloggers.json

---

src/main/resources/blogs/bloggers.json

Update bloggers.json - mjasion.pl

---

src/main/resources/blogs/bloggers.json

update blog information

---

src/main/resources/blogs/bloggers.json

Change after blog name changed

Changed blog name

---

src/main/resources/blogs/bloggers.json

In this PR, I'm updating path to the RSS feed of my blog, which was recently migrated from hexo to hugo :).

updating path to the RSS feed for the blog of Piotr Wittchen

---

src/main/resources/blogs/companies.json

Hello JVM Bloggers,
I'd like to add Cognifide Tech blog to the companies section.
Let me know if you have any questions.
Thank you

Add Cognifide Tech blog

---

src/main/java/com/jvm_bloggers/frontend/common_components/PublishedBlogPostLink.java
src/main/java/com/jvm_bloggers/utils/CleanString.java
src/main/resources/blogs/podcasts.json
src/test/groovy/com/jvm_bloggers/utils/CleanStringSpec.groovy

After testing with real world examples I increased the acceptable limit of upper case letters to 35%. I haven't removed emojis yet, because there is separate issue created for that.

Should lower case post titles that exceed upper case limit #609

---

src/main/resources/blogs/bloggers.json

Krzysztof Ślusarski blog

---

src/main/resources/blogs/bloggers.json

Mój blog - głównie związany z Javą i technologią Liferay, ale bywają także wpisy bardziej "technology agnostic" przykładowo dziś opublikowałem wpis o GraphQL (o którym ostatnio miałem okazje opowiadać na MeetJS)

Add personal blog: https://pydyniak.com

---

src/main/resources/blogs/bloggers.json

Update RSS feed

---

src/main/resources/blogs/companies.json

Add ViacomCBS blog

---

src/main/resources/blogs/bloggers.json

Recently, I've changed my domain to blog.wpanas.eu and moved from Jekyll to GoHugo

Change feed url for blog.wpanas.eu

---

src/main/resources/blogs/bloggers.json

Request to add personal blog - [stepniewski.tech](https://stepniewski.tech/blog/)

Adds stepniewski.tech blog

---

src/main/resources/blogs/podcasts.json

Podcast page: https://devstory.pl/

Add Dev Story podcast

---

src/main/resources/blogs/companies.json

It already contains some nice Java, Kotlin & architecture articles.

Add Glovo Engineering blog

---

src/main/resources/blogs/bloggers.json
src/main/resources/blogs/podcasts.json

- remove blog at michalik.tech
- add blog at devspeaker.pl
- add feed from my new YT channel;

Add DevSpeaker.pl and Jarek Michalik YT

---

src/main/java/com/jvm_bloggers/frontend/public_area/social_meta_data/DefaultSocialMetaData.java
src/main/java/com/jvm_bloggers/frontend/public_area/social_meta_data/SocialMetaDataHeadRenderer.java
src/main/java/com/jvm_bloggers/utils/WicketUtilities.java
src/test/groovy/com/jvm_bloggers/utils/WicketUtilitiesSpec.groovy

#742 Facebook sharing fixed

---

src/main/java/com/jvm_bloggers/core/newsletter_issues/NewsletterIssueFactory.java
src/main/java/com/jvm_bloggers/core/rss/AggregatedRssFeedProducer.java
src/main/java/com/jvm_bloggers/core/rss/converters/SyndFeedToJsonConverter.java
src/main/java/com/jvm_bloggers/core/rss/fetchers/HttpRssFetcherWithoutSslVerification.java
src/main/java/com/jvm_bloggers/frontend/common_components/infinite_scroll/InfinitePaginationPanel.java
src/test/groovy/com/jvm_bloggers/core/github/ContributorsServiceSpec.groovy
src/test/groovy/com/jvm_bloggers/core/rss/SyndFeedProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetContentGeneratorSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetProducerSpec.groovy
src/test/groovy/com/jvm_bloggers/utils/CleanStringSpec.groovy

This change focuses on utilizing both new methods introduced in recent Java versions as well as idiomatic Groovy syntax for lists.
(The last commit related to instanceOf pattern matching doesn't really fit but it doesn't feel like it deserves a separate PR).

Collections refactoring

---

build.gradle
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostFactory.java
src/main/java/com/jvm_bloggers/core/utils/EmojiRemover.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostFactorySpec.groovy
src/test/groovy/com/jvm_bloggers/core/utils/EmojiRemoverSpec.groovy

Fixes jvm-bloggers#639
* remove emojis from blog posts' titles
* use `emoji-java` in version `5.1.1`
* remove some spotted dead code around `BlogPostFactory`

Introduce remover of emojis

---

buildSrc/src/main/groovy/com/jvm_bloggers/validation/JsonValidator.groovy
buildSrc/src/main/groovy/com/jvm_bloggers/validation/ValidatorMessageTranslator.groovy
buildSrc/src/test/groovy/com/jvm_bloggers/validation/JsonValidatorSpec.groovy
buildSrc/src/test/groovy/com/jvm_bloggers/validation/ValidatorMessageTranslatorSpec.groovy

* continuation of https://github.com/jvm-bloggers/jvm-bloggers/pull/734
* JSON validator message improvements introduced
* unfortunately, the validator's API is not too flexible, therefore messages are not perfect, but at least they're now way more readable than previously

Blogs data validation improvements

---

src/main/resources/blogs/bloggers.json

include posts with jvm-blogger tag only

update rss for kuba86

---

src/main/resources/blogs/bloggers.json

Added Michał Talaga personal blog on dev.to

Update bloggers.json to add Michał Talaga blog

---

src/main/resources/blogs/bloggers.json

Hi,
I'd like to add technical notes blog that I'm creating together with @tomaszmichalak.
Thank you.

Add hands-on architects blog

---

src/main/resources/blogs/companies.json

We are migrating out of WordPress to Substack Platform

Update companies.json - new vived.io link

---

src/main/resources/blogs/bloggers.json

Include Robert Niestrój blog into JVM Bloggers

Robert Niestrój blog

---

src/main/resources/blogs/bloggers.json

I've moved my site from devrev.pl to devreview.pl.

Rebranding from devrev.pl to devereview.pl

---

src/main/resources/blogs/bloggers.json

Jak w temacie - coś się kończy, coś się (znów) zaczyna.

Removed retired Chlebik blog and added new one
