jvm-bloggers/jvm-bloggers

gradle.properties
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/BlogPostsFetcher.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/mailing/BlogSummaryMailGenerator.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/mailing/MailingPageRequestHandler.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/mailing/MailingTemplateModel.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/admin/moderation/ModerationPage.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/login/LoginPage.java
src/main/resources/application.yaml
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/SpringContextAwareSpecification.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/jasypt/JasyptShouldEncryptPropertiesSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/mailing/IssueNumberRetrieverSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/mailing/domain/MailingAddressRepositorySpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/view/login/LoginPageSpec.groovy
src/test/java/pl/tomaszdziurko/jvm_bloggers/JvmBloggersApplicationTests.java
src/test/resources/application-test.yaml

1. By code clean-up I meant:
- removing unused variables
- adding missing type parameters to variable declarations
- other warnings compiler complained about
2. Test cases that relies on Spring container were refactored to remove repetitiveness (mainly duplicated `setupSpec` methods and `@ContextConfiguration` annotations in each test) by pulling common parts to new [`SpringContextAwareSpecification`](https://github.com/goostleek/jvm-bloggers/blob/code-cleanup/src/test/groovy/pl/tomaszdziurko/jvm_bloggers/SpringContextAwareSpecification.groovy) class. Additionally tests related _application.yaml_ file was renamed to _application-test.yaml_ to resolve strange Eclipse related warnings about duplicated resources that led to failed unit tests when using IDE to launch tests.
3. I have also …

Code clean-up and tests refactoring

---

build.gradle
infinitest.args

The fix provided in [#974ad16](https://github.com/goostleek/jvm-bloggers/commit/9b34a11f9c122bc8291ad539fe2d5a9b8a6f0e52) was not complete. Although it fixes running application from _bootRun_ task it has no effect on _test_ task as unit tests are running in a separate JVM and `file.encoding` property is not copied to forked process so we should provide it explictely for _test_ task otherwise unit tests that depend on Spring container will fail (on environments with non UTF-8 default encoding) with the following error:
```
java.lang.IllegalStateException: Failed to load ApplicationContext
at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
at …
```

Fixed tests under development environments that uses non UTF-8 encoding

---

build.gradle
config/checkstyle/checkstyle.xml
config/formatters/How-to.md
config/formatters/eclipse-java-google-style.xml
config/formatters/intellij-java-google-style.xml
config/formatters/scripts/copyIdeaFormatterMacOS.sh

This is a WIP towards common formatting rules.
1. New checkstyle based on Google Java Style Guide 
Changes there (as in commits in this PR):
- Raise errors when checkstyle fails
- Classes from google.com are no longer treated in a special way in import ordering
- Indentation is based on 4-spaces (Google currently advices 2-spaces base indentation)
- Javadocs are not required
There are two Eclipse/IntelliJ formatters that are currently almost in line with checkstyle checks. They will requires some tuning (especially indentation and import ordering) but we need to agree on the checkstyle file first.
Things that I want to discuss (taken from failing checkstyle report):
1. If you have any comments to the changes already applied to the original checkstyle file, please write them in this topic. …

Issue 112 introduce common formatting, closes #112

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPost.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepository.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepositorySpec.groovy

Just included _approved_ property in _order by_ clause.
Posts are correctly sorted because of the following positioning of NULL value:
> By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

issue/#118 Blog posts sorted by (approved, publishedDate)

---

src/test/groovy/pl/tomaszdziurko/jvm_bloggers/SpringContextAwareSpecification.groovy

I have also prepared a test case for this, but I decided not to add it to PR (we don't want to test Spring framework, do we?). It's only a proof that the solution works. You may use it to check it yourself.
```
@Subject
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class TestCaseIsolationChecker extends SpringContextAwareSpecification {
@Autowired
BlogRepository blogRepository
def "1. Add blog to repository"() {
given:
def blog = Blog.builder()
.jsonId(1L)
.author("author")
.rss("rss")
.dateAdded(new NowProvider().now())
.blogType(BlogType.PERSONAL)
.build()
when:
blogRepository.save(blog)
then:
blogRepository.count() == 1
}
def "2. Should be no blogs in repository"() {
expect:
blogRepository.count() == 0
}
}
```

Unit test cases isolation

---

src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/AggregatedRssFeedProducer.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/BlogPostsController.java
src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepository.java
src/main/resources/application.yaml
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/AggregatedRssFeedProducerSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/BlogPostsControllerSpec.groovy

- the limit is configurable by `generated.rss.entries.limit` property in [`application.yaml`](https://github.com/goostleek/jvm-bloggers/blob/issue/%23154/limit-rss-entries/src/main/resources/application.yaml#L17)
- RSS consumer can override the limit on HTTP request level by appending `limit` query parameter, eg:
- `http://localhost:8080/pl/rss?limit=10`
- `http://localhost:8080/pl/rss?limit=0` to get all approved blog entries

Added support for limiting generated RSS feed entries count, fixes #154

---

build.gradle
src/main/java/pl/tomaszdziurko/jvm_bloggers/view/login/attack/stream/BruteForceAttackEventStreamManager.java
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/MockSpringContextAwareSpecification.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/view/login/LoginPageSpec.groovy
src/test/groovy/pl/tomaszdziurko/jvm_bloggers/view/login/attack/stream/BruteForceAttackEventStreamManagerSpec.groovy

This is a new way of testing Wicket components. There is no need to start entire Spring context which is a really heavy object. This way Wicket components test execution is a matter of seconds. Additional advantage is that we don't have to provide external Spring configuration which is specific for unit tests only, we can provide mocks at unit test level instead (see example of [`setupContext`](https://github.com/tdziurko/jvm-bloggers/compare/master...goostleek:mock-spring-context-aware-spec?expand=1#diff-1a3a4133b1c845c094f336bcfdf52e74R41)). We also don't have to provide [this dirty hack](https://github.com/tdziurko/jvm-bloggers/pull/182/files#diff-1a3a4133b1c845c094f336bcfdf52e74L35) to workaround [WICKET-605](https://issues.apache.org/jira/browse/WICKET-605). **And finally, the most …

MockSpringContextAwareSpecification introduced

---

src/main/resources/blogs/bloggers.json

new blog domain (and redirect from old one) caused new blog entry to be added twice to weekly dig

blog domain name update

---

build.gradle

By default Liquibase uses _stderr_ to print its logging statements. I have added a [dependency](https://github.com/mattbertolini/liquibase-slf4j) to the extension forcing Liquibase to use application configured logger instead.

Improved Liquibase logging

---

src/main/java/com/jvm_bloggers/core/InitialBlogDataPopulationTrigger.java

This is the fix for _NPE_ which revealed itself in #271. Database population trigger was delayed until Spring application context is fully initialized to prevent _NPE_ race condition in [`SpringApplicationContext`](https://github.com/jvm-bloggers/jvm-bloggers/blob/17aabd22deeb5da75864a6dd102a54708cf42bf5/src/main/java/com/jvm_bloggers/SpringApplicationContext.java#L18) component.

Fixed NPE on application boot when the database contains no blog posts

---

src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java

I noticed that blogs are fetched by fire-forget (stream foreach) so why not parallelize it?
This improves fetching time by an order of magnitude.

Significantly improved blogs fetching performance

---

CONTRIBUTING.md
src/main/resources/db/changelog/db.changelog.xml

Unfortunetly I cannot use 'addUniqueConstraint' and 'dropUniqueConstraint' which is a case of the issue. Only way I found to do that, without crashing tests, was to add new column with new ~~implict~~ explicit constraint.
+ liquibase guidelines added

Issue #293

---

src/main/java/com/jvm_bloggers/core/data_fetching/http/ProtocolSwitchingAwareConnectionRedirectHandler.java
src/main/java/com/jvm_bloggers/core/rss/SyndFeedProducer.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/http/ProtocolSwitchingAwareConnectionRedirectHandlerSpec.groovy

According to the [documentation](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setRequestProperty-java.lang.String-java.lang.String-) current approach would only set last value passed. If we really need multi value headers we should merge them into one but I don't think we need it.

Allowing only single values for http headers.

---

build.gradle
src/main/java/com/jvm_bloggers/GithubClient.java
src/main/java/com/jvm_bloggers/JvmBloggersConfiguration.java
src/main/java/com/jvm_bloggers/MailingClient.java
src/main/java/com/jvm_bloggers/core/github/ContributorsService.java
src/main/java/com/jvm_bloggers/core/github/GithubAuthenticationFilter.java
src/main/java/com/jvm_bloggers/core/github/GithubProperties.java
src/main/java/com/jvm_bloggers/core/mailing/sender/MailgunSender.java
src/main/java/com/jvm_bloggers/entities/github/Contributor.java
src/main/java/com/jvm_bloggers/frontend/public_area/common_layout/HeaderFrontend.html
src/main/java/com/jvm_bloggers/frontend/public_area/common_layout/HeaderFrontend.java
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorDetails.html
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorDetails.java
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorsPage.html
src/main/java/com/jvm_bloggers/frontend/public_area/contributors/ContributorsPage.java
src/main/resources/application.yaml
src/test/groovy/com/jvm_bloggers/core/github/ContributorsServiceSpec.groovy
src/test/groovy/com/jvm_bloggers/core/github/GithubAuthenticationFilterSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/public_area/contributors/ContributorDetailsSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/public_area/contributors/ContributorsPageSpec.groovy

This is a MVP implementation. This could be further enhanced with ie. adding contributors full name instead of only login, but this would require N+1 calls to GitHub API.
Using of access token is note required, but I'd consider this a good idea in general.
One impotent thing is new config for cache invalidation `cache.spec` which affects also cache used in `AggregatedRssFeedProducer`. Personally I think that previous behavior was a bug as cache in `AggregatedRssFeedProducer` was never invalidated.

Support for contributors fetching thought GitHub API. Fix #288

---

src/main/java/com/jvm_bloggers/domain/query/NewsletterIssueNumber.java
src/main/java/com/jvm_bloggers/domain/query/published_newsletter_issue/PublishedNewsletterIssueQuery.java
src/main/java/com/jvm_bloggers/entities/newsletter_issue/NewsletterIssueRepository.java
src/main/java/com/jvm_bloggers/frontend/public_area/HomePage.java
src/main/java/com/jvm_bloggers/frontend/public_area/HomePageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/NewsletterIssuePage.java
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/NewsletterIssuePageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/newsletter_panel/NewsletterIssueNavigationLink.java
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/newsletter_panel/NewsletterIssuePanel.html
src/main/java/com/jvm_bloggers/frontend/public_area/newsletter_issue/newsletter_panel/NewsletterIssuePanel.java
src/test/groovy/com/jvm_bloggers/domain/query/published_newsletter_issue/PublishedNewsletterIssueQuerySpec.groovy
src/test/groovy/com/jvm_bloggers/entities/newsletter_issue/NewsletterIssueRepositorySpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/public_area/newsletter_issue/NewsletterIssuePageSpec.groovy

PR which adds previous and next links at the bottom of `NewsletterIssuePanel`

Newsletter issue navigation links. Closes #319

---

src/main/java/com/jvm_bloggers/core/InitialBlogDataPopulationTrigger.java
src/main/java/com/jvm_bloggers/core/data_fetching/blog_posts/BlogPostsFetchingScheduler.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataFetchingScheduler.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/json_data/BloggerEntry.java
src/main/java/com/jvm_bloggers/core/data_fetching/http/ProtocolSwitchingAwareConnectionRedirectHandler.java
src/main/java/com/jvm_bloggers/core/mailing/BlogSummaryMailGenerator.java
src/main/java/com/jvm_bloggers/core/newsletter_issues/NewsletterIssueFactory.java
src/main/java/com/jvm_bloggers/core/rss/AggregatedRssFeedProducer.java
src/main/java/com/jvm_bloggers/core/rss/BlogPostsController.java
src/main/java/com/jvm_bloggers/domain/query/published_newsletter_issue/PublishedNewsletterIssueBuilder.java
src/main/java/com/jvm_bloggers/frontend/admin_area/blogs/BlogsPageRequestHandler.java
src/main/java/com/jvm_bloggers/frontend/admin_area/login/attack/BruteForceAttackMailGenerator.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingAddressPageRequestHandler.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingPageRequestHandler.java
src/main/java/com/jvm_bloggers/frontend/admin_area/moderation/BlogPostItemPopulator.java
src/main/java/com/jvm_bloggers/frontend/admin_area/moderation/ModerationPageRequestHandler.java

`@Autowired` is no longer needed on Spring constructors so removing it.
I cannot see any particular reason for `@NoArgConstructor` on `BlogsPageRequestHandler`, so removing this one as well.

Removing unnecessary `@Autowired` annotation from generated constructors

---

src/main/java/com/jvm_bloggers/core/rss/BlogPostsController.java
src/test/groovy/com/jvm_bloggers/core/rss/BlogPostsControllerSpec.groovy

Adds xml as a first produced media type in BlogPostsController.java, makes test more specific by using real "Accept" header from browser, fixes #395

Make xml format as a default in RSS, fixes #395

---

.travis.yml

I noticed that some builds that work on local machine are failing on CI with following message:
`Process 'Gradle Test Executor 2' finished with non-zero exit value 137`
which can indicate that build is using too many resources. 
This issue can be related to [recent change](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) in travis where default distribution is now `trusty`. One of the suggestion to fix this was to use [sudo: required](https://docs.travis-ci.com/user/reference/trusty#Fully-virtualized-via-sudo%3A-required) command.

Force build to run on isolated GCE VM.

---

src/main/java/com/jvm_bloggers/frontend/common_components/infinite_scroll/InfinitePaginationPanel.html
src/main/java/com/jvm_bloggers/frontend/common_components/infinite_scroll/InfinitePaginationPanel.java
src/main/java/com/jvm_bloggers/frontend/common_components/infinite_scroll/InfiniteScrollingBehavior.java
src/main/java/com/jvm_bloggers/frontend/common_components/infinite_scroll/js/infinite-scroll-event-listener.js
src/test/groovy/com/jvm_bloggers/frontend/common_components/InfinitePaginationPanelSpec.groovy

Today infinity scroll stops loading more data when an error is returned for requesting lastPage + 1, this is ok but this print WARN message to the logs. This PR introduces handling this scenario in following way:
1) When number of pages > 1 then disable infinite scroll when on second to the last page
2) When number of pages <= 1 then do not add infinity scroll behaviour

Infinite scroll respect last page.

---

src/main/resources/blogs/companies.json

Sii's blog URL has changed. Feed in previous URL is redirecting correctly, but one of article from the blog didn't showed up on jvm-bloggers issue.
Hope this modification will fix it.
Thx

Updated Sii feed URL

---

src/main/resources/blogs/bloggers.json

Adding my own blog feed, but also noticed there is a trailing space before my entry, hence it's removed.

Add Dawid Pura's blog; remove trailing space from kodujze rss entry

---

src/main/java/com/jvm_bloggers/core/social/twitter/TweetContentGenerator.java
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetContentGeneratorSpec.groovy

Fixes duplicates in personal blogs Twitter handles.
Example: @wololock in https://twitter.com/JVM_bloggers/status/1045618546888323075

personal blogs twitter handles duplications fix

---

src/main/resources/blogs/companies.json

Previous link pointed to `all` blog posts, sometimes not related to programming

Fixed Espeo blog to show only dev topics

---

build.gradle
src/main/java/com/jvm_bloggers/core/data_fetching/blogs/json_data/BloggerEntry.java
src/main/java/com/jvm_bloggers/core/newsletter_issues/NewsletterIssueFactory.java
src/main/java/com/jvm_bloggers/core/social/twitter/publisher/Twitter4jPublisher.java
src/main/java/com/jvm_bloggers/domain/query/blog_statistics_for_listing/BlogStatisticsForListingQuery.java
src/main/java/com/jvm_bloggers/frontend/admin_area/mailing/MailingPageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/admin_area/moderation/ModerationPageRequestHandler.java
src/main/java/com/jvm_bloggers/frontend/public_area/blogs/AbstractBlogsPageBackingBean.java
src/main/java/com/jvm_bloggers/frontend/public_area/varia_suggestion/VariaSuggestionPageBackingBean.java
src/test/groovy/com/jvm_bloggers/core/utils/LocalDateToTimestampConverterSpec.groovy
src/test/groovy/com/jvm_bloggers/frontend/admin_area/login/attack/BruteForceAttackMailGeneratorSpec.groovy

Changes: 
- update Lombok to 1.18.8
- add changes required for compatibility with new version of Lombok
- change old-style constructor autowiring
- remove @Autowire if not required
- update test that fails in other timezone

Update Lombok version and remove old-style constructor autowiring

---

src/main/resources/blogs/companies.json

Kindly please add Tornimo blog to JVM Bloggers. We used to publish small product updates there and recently started posting longer articles. So far about [CDN](https://tornimo.io/blog/are-you-using-your-cdn-wrong-get-more-out-of-your-provider/) and [UX](https://tornimo.io/blog/its-not-always-about-bad-design-performance-in-user-experience/). In time Java content should also appear there.
Thanks!

Tornimo.io news & blog

---

src/test/groovy/com/jvm_bloggers/ObjectMother.groovy
src/test/groovy/com/jvm_bloggers/entities/blog/BlogSpec.groovy
src/test/groovy/com/jvm_bloggers/entities/blog_post/BlogPostRepositorySpec.groovy

that generates common data for Blog and BlogPost test objects. Easy data customization is allowed via passing an optional Map parameter to factory methods.
Example usage shown on two tests: BlogPostRepositorySpec and BlogSpec

Introduce ObjectMother class for test data generation

---

src/main/java/com/jvm_bloggers/core/social/twitter/TweetContentGenerator.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/json_data/JsonBlogsDataFileValidationSpec.groovy
src/test/groovy/com/jvm_bloggers/core/social/twitter/TweetContentGeneratorSpec.groovy

Resolves #463
Since twitter messages are increased to 280 chars, there is no need for shorter message template and  template for `N` messages.

Remove unused twitter template message

---

docker-compose.yml

2.0.0 has been released: https://github.com/caddyserver/caddy/releases/tag/v2.0.0
There is a dedicated tag for 2.x which should be more pertinent over time (in the context of backward compatibility):
https://hub.docker.com/_/caddy?tab=tags

Switch caddy Docker image from latest to 2

---

src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java
src/test/groovy/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdaterSpec.groovy

I'm not sure if this brute-force in BloggersDataUpdater#isModerationRequired is a good idea.
Maybe create version with "banned list" in json file? It's not too complicated for this simple issue?

Add setting moderation enabled for blogs from medium, #574

---

src/main/resources/blogs/bloggers.json

Removing szimano.org (dead link)

---

src/main/resources/blogs/companies.json

Hi,
Cognifide has recently rebranded to Wunderman Thompson Technology and we have redesigned blog page under the new address.

Cognifide rebranded to Wunderman Thompson Technology

---

src/main/resources/blogs/bloggers.json
src/main/resources/blogs/companies.json

We'll add a redirect at the old address, but it's better to use the new address directly anyway

Updated allegro blog RSS address

---

src/main/resources/blogs/bloggers.json

Author no longer writes in Java and the last 10 or so articles are abot Python: https://mmazurek.dev/kiedys-programowalem-w-javie-czyli-o-zmianie-jezyka-wiodacego/

Removing mmazurek.dev

---

build.gradle

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Even thought they decided - under the pressure - to keep it as a read-only
repository "indefinitely".

Remove deprecated jcenter

---

src/main/resources/blogs/bloggers.json

I've changed the blog engine from WP to Hugo, and I would like to ask to change the address here, so I won't have to search for workarounds to set a custom feed address.
URLs of particular posts should remain the same as before, so I hope there won't be any mess here.
Thank you!

Change konkit.tech feed address

---

src/main/resources/blogs/bloggers.json

Po przeniesieniu bloga na GH pages in wyjściu z wordpressa.

Aktualizacja adresu feeda

---

buildSrc/src/test/groovy/com/jvm_bloggers/validation/ValidatorMessageTranslatorSpec.groovy

* fixes a "small" issue with `ValidatorMessageTranslatorSpec` tests that was making them not so deterministic
* the issue was introduced within #747

Fixes ValidatorMessageTranslatorSpec tests

---

build.gradle
buildSrc/build.gradle
gradle/wrapper/gradle-wrapper.properties

* bump up Spring Boot version to `2.7.6`
* bump up Gradle wrapper to version `7.6`
* bump up `io.spring.dependency-management` plugin version to `1.1.0`
* bump up `caffeine` to version `3.1.2`
* bump up `hibernate-search` to version `5.11.11.Final`
* bump up `jersey` to version `2.37`
* bump up base Docker image to `eclipse-temurin:17.0.5_8-jre-alpine`
PS. We are a bit blocked to migrate to Spring Boot 3 due to the fact that Wicket is not migrated to `jakarta` yet (when the new Spring Boot is) -> see: https://issues.apache.org/jira/browse/WICKET-6882

Update Spring Boot to version 2.7.6

---

src/main/resources/blogs/bloggers.json

My blog is not strictly JVM related, but since it covers very general IT and development topics, I think it could also interest Java/Kotlin devs.

Add swistak.codes to bloggers.json

---

src/main/java/com/jvm_bloggers/frontend/public_area/AbstractFrontendPage.html

Currently it looks like that
And after change ribbon is fixed

FIX "Fork me on Github" ribbon
